const ACCESS_TOKEN = "access_token";
const LONG_EXPIRY_DATE = 60;
const USER_SSO = "user_sso";
const VALID_ACCESS_TOKEN_RESPONSE = "VALID";
const EXPIRED_ACCESS_TOKEN_RESPONSE = "EXPIRED";
const ACTION_ADD_TO_CART = "ACCTION_ADD_TO_CART";
const ACTION_GET_CART = "ACTION_GET_CART";
const ACTION_UPDATE_ITEM_CART = "ACTION_UPDATE_ITEM_CART";
const ACTION_REMOVE_FROM_CART = "ACTION_REMOVE_FROM_CART";
const ACTION_CLEAR_CART = "ACTION_CLEAR_CART";
/* USER ACTION */
const ACTION_GET_USER_INFORMATION = "ACTION_GET_USER_INFORMATION";
const ACTION_SET_USER_INFORMATION = "ACTION_SET_USER_INFORMATION";
const ACTION_UPDATE_USER_INFORMATION = "ACTION_UPDATE_USER_INFORMATION";
const ACTION_DELETE_USER_INFORMATION = "ACTION_DELETE_USER_INFORMATION";

export default {
    ACCESS_TOKEN : ACCESS_TOKEN,
    LONG_EXPIRY_DATE : LONG_EXPIRY_DATE,
    USER_SSO: USER_SSO,
    VALID_ACCESS_TOKEN_RESPONSE: VALID_ACCESS_TOKEN_RESPONSE,
    EXPIRED_ACCESS_TOKEN_RESPONSE: EXPIRED_ACCESS_TOKEN_RESPONSE,
    ACTION_ADD_TO_CART : ACTION_ADD_TO_CART,
    ACTION_GET_CART    : ACTION_GET_CART,
    ACTION_UPDATE_ITEM_CART : ACTION_UPDATE_ITEM_CART,
    ACTION_REMOVE_FROM_CART : ACTION_REMOVE_FROM_CART,
    ACTION_CLEAR_CART : ACTION_CLEAR_CART,

    ACTION_GET_USER_INFORMATION: ACTION_GET_USER_INFORMATION,
    ACTION_SET_USER_INFORMATION: ACTION_SET_USER_INFORMATION,
    ACTION_UPDATE_USER_INFORMATION: ACTION_UPDATE_USER_INFORMATION,
    ACTION_DELETE_USER_INFORMATION: ACTION_DELETE_USER_INFORMATION
};

